log:
  # level of logging that nextlinux-ecs-inventory will do  { 'error' | 'info' | 'debug }
  level: "info"

  # location to write the log file (default is not to have a log file)
  file: ""

nextlinux:
  # nextlinux enterprise api url  (e.g. http://localhost:8228)
  url: $NEXTLINUX_ECS_INVENTORY_NEXTLINUX_URL

  # nextlinux enterprise username
  user: $NEXTLINUX_ECS_INVENTORY_NEXTLINUX_USER

  # nextlinux enterprise password
  password: NEXTLINUX_ECS_INVENTORY_NEXTLINUX_PASSWORD

  # nextlinux enterprise account that the inventory will be sent
  account: $NEXTLINUX_ECS_INVENTORY_NEXTLINUX_ACCOUNT

  http:
    insecure: true
    timeout-seconds: 10

# the aws region
region: $NEXTLINUX_ECS_INVENTORY_REGION

# frequency of which to poll the region
polling-interval-seconds: 300

quiet: false
