log:
  level: "info"
  # location to write the log file (default is not to have a log file)
  file: "./anchore-ecs-inventory.log"

anchore:
  url: http://localhost:8228
  user: admin
  password: $ANCHORE_ECS_INVENTORY_PASSWORD
  http:
    insecure: true
    timeout-seconds: 10
