version: '2.1'

services:
  nextlinux-ecs-inventory:
    image: docker.io/nextlinux/ecs-inventory:latest
    container_name: nextlinux-ecs-inventory
    volumes:
      - ./nextlinux-ecs-inventory.yaml:/.nextlinux-ecs-inventory.yaml
      - ./aws.config:/.aws/credentials
    environment:
      NEXTLINUX_ECS_INVENTORY_NEXTLINUX_URL: ${NEXTLINUX_ECS_INVENTORY_NEXTLINUX_URL:-http://host.docker.internal:8228}
      NEXTLINUX_ECS_INVENTORY_NEXTLINUX_USER: ${NEXTLINUX_ECS_INVENTORY_NEXTLINUX_USER:-admin}
      NEXTLINUX_ECS_INVENTORY_NEXTLINUX_PASSWORD: ${NEXTLINUX_ECS_INVENTORY_NEXTLINUX_PASSWORD:-foobar}
      NEXTLINUX_ECS_INVENTORY_NEXTLINUX_ACCOUNT: ${NEXTLINUX_ECS_INVENTORY_NEXTLINUX_ACCOUNT:-admin}
      NEXTLINUX_ECS_INVENTORY_REGION: ${NEXTLINUX_ECS_INVENTORY_REGION:-eu-west-2}
